language: go

install:
  - sh -c '[ -d $GOPATH/bin ] || mkdir $GOPATH/bin'
  - curl https://glide.sh/get | sh
  - cd $GOPATH/src/github.com/osrg/goplane && glide install

script:
  - cd $GOPATH/src/github.com/osrg/goplane && go test $(glide novendor)

matrix:
  allow_failures:
  - go: tip
  include:
  - go: 1.5
    env:
    - GO15VENDOREXPERIMENT=1
  - go: 1.6
  - go: 1.7
  - go: tip
  - go: 1.7
    sudo: required
    env:
    - TEST=test/netlink/evpn_vxlan_test.py
    services:
    - docker
    script: test/travis_script.sh
  - go: 1.7
    sudo: required
    env:
    - TEST=test/netlink/multipath_test.py
    services:
    - docker
    script: test/travis_script.sh
  - go: 1.7
    sudo: required
    env:
    - TEST=test/netlink/unnumbered_test.py
    services:
    - docker
    script: test/travis_script.sh

go_import_path: github.com/osrg/goplane
